# Generated by Django 4.2.13 on 2024-06-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=4000)),
                ('date', models.DateField(verbose_name='Dream date')),
                ('type', models.CharField(choices=[('J', 'Just a Dream'), ('N', 'Nightmare'), ('R', 'Recurring'), ('C', 'Comforting'), ('W', 'Weird')], default='J', max_length=1)),
            ],
        ),
    ]
